
services:
  caddy:
    image: caddy:2-alpine
    env_file:
      - ../.env
    ports:
      - "80:80"
      - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    networks:
      - kita-proxy
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  kita-proxy:
    external: true