"""suggestion bool accepted changed to enum status

Revision ID: 27c0aa2c49ae
Revises: a1734cccf7b3
Create Date: 2026-06-21 07:59:19.123873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c0aa2c49ae'
down_revision: Union[str, Sequence[str], None] = 'a1734cccf7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE suggestion_status AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED')")

    op.add_column('suggestion', sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='suggestion_status', create_constraint=True), server_default='PENDING', nullable=False))
    op.drop_index(op.f('ix_suggestion_accepted'), table_name='suggestion')
    op.create_index(op.f('ix_suggestion_status'), 'suggestion', ['status'], unique=False)
    op.drop_column('suggestion', 'accepted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion', sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_suggestion_status'), table_name='suggestion')
    op.create_index(op.f('ix_suggestion_accepted'), 'suggestion', ['accepted'], unique=False)
    op.drop_column('suggestion', 'status')

    op.execute("DROP TYPE suggestion_status")
    # ### end Alembic commands ###
