"""indexes

Revision ID: 300a39c811ff
Revises: 9a0bf602b58a
Create Date: 2026-08-11 20:20:54.703964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300a39c811ff'
down_revision: Union[str, Sequence[str], None] = '9a0bf602b58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestion_status'), table_name='suggestion')
    op.create_index('ix_suggestion_bot_status', 'suggestion', ['bot_id', 'status'], unique=False)
    op.create_index('ix_user_profile_bot_role', 'user_profile', ['bot_id', 'role'], unique=False)
    op.create_index(op.f('ix_userbot_active'), 'userbot', ['active'], unique=False)
    op.create_index(op.f('ix_userbot_owner_id'), 'userbot', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userbot_owner_id'), table_name='userbot')
    op.drop_index(op.f('ix_userbot_active'), table_name='userbot')
    op.drop_index('ix_user_profile_bot_role', table_name='user_profile')
    op.drop_index('ix_suggestion_bot_status', table_name='suggestion')
    op.create_index(op.f('ix_suggestion_status'), 'suggestion', ['status'], unique=False)
    # ### end Alembic commands ###
