"""initial_migration

Revision ID: 6f55fa2adf80
Revises: 
Create Date: 2026-02-15 19:16:29.919823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f55fa2adf80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'BANNED', name='user_role', create_constraint=True), server_default='USER', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('suggestion',
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('media_group_id', sa.String(), nullable=True),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestion_accepted'), 'suggestion', ['accepted'], unique=False)
    op.create_index(op.f('ix_suggestion_author_id'), 'suggestion', ['author_id'], unique=False)
    op.create_table('media',
    sa.Column('filetype', sa.String(), nullable=False),
    sa.Column('telegram_file_id', sa.String(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_suggestion_id'), 'media', ['suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_suggestion_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_suggestion_author_id'), table_name='suggestion')
    op.drop_index(op.f('ix_suggestion_accepted'), table_name='suggestion')
    op.drop_table('suggestion')
    op.drop_table('users')
    # ### end Alembic commands ###
