"""suggestion forwarded_from

Revision ID: 8506a9814776
Revises: 59283212dad1
Create Date: 2026-03-18 01:43:40.065161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8506a9814776'
down_revision: Union[str, Sequence[str], None] = '59283212dad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion', sa.Column('forwarded_from', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestion', 'forwarded_from')
    # ### end Alembic commands ###
