"""Userbot banned

Revision ID: 9a0bf602b58a
Revises: b18a0a643aa1
Create Date: 2026-08-06 16:47:22.732808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0bf602b58a'
down_revision: Union[str, Sequence[str], None] = 'b18a0a643aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbot', sa.Column('banned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userbot', 'banned')
    # ### end Alembic commands ###
