"""add suggestion anonymous

Revision ID: a1734cccf7b3
Revises: ca79faf2b42e
Create Date: 2026-06-17 09:18:21.241514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1734cccf7b3'
down_revision: Union[str, Sequence[str], None] = 'ca79faf2b42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestion', sa.Column('anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestion', 'anonymous')
    # ### end Alembic commands ###
