"""Add UserBot, UserProfile. Suggestion and Media bot_id

Revision ID: a22fdf38882f
Revises: 27c0aa2c49ae
Create Date: 2026-07-22 22:01:54.860976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a22fdf38882f'
down_revision: Union[str, Sequence[str], None] = '27c0aa2c49ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('prefer_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_bot_blocked', sa.Boolean(), nullable=True),
    sa.Column('role', postgresql.ENUM('USER', 'ADMIN', 'BANNED', name='user_role', create_type=False), server_default='USER', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'user_id', name='uq_user_profile_bot_user')
    )
    op.create_table('userbot',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('media', sa.Column('bot_id', sa.BigInteger(), nullable=False))
    op.add_column('suggestion', sa.Column('bot_id', sa.BigInteger(), nullable=False))
    op.drop_column('users', 'role')
    op.drop_column('users', 'prefer_anonymous')
    op.drop_column('users', 'is_bot_blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_bot_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('prefer_anonymous', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', postgresql.ENUM('USER', 'ADMIN', 'BANNED', name='user_role', create_type=False), server_default=sa.text("'USER'::user_role"), autoincrement=False, nullable=False))
    op.drop_column('suggestion', 'bot_id')
    op.drop_column('media', 'bot_id')
    op.drop_table('userbot')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
