"""UserBot bot_id unique

Revision ID: b18a0a643aa1
Revises: a22fdf38882f
Create Date: 2026-07-30 17:36:35.487118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18a0a643aa1'
down_revision: Union[str, Sequence[str], None] = 'a22fdf38882f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'userbot', ['bot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userbot', type_='unique')
    # ### end Alembic commands ###
