"""indexes

Revision ID: bacc85ee8bb7
Revises: 220f27c0a5d8
Create Date: 2026-02-08 20:23:00.944106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bacc85ee8bb7'
down_revision: Union[str, Sequence[str], None] = '220f27c0a5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_media_suggestion_id'), 'media', ['suggestion_id'], unique=False)
    op.create_index(op.f('ix_suggestion_accepted'), 'suggestion', ['accepted'], unique=False)
    op.create_index(op.f('ix_suggestion_author_id'), 'suggestion', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggestion_author_id'), table_name='suggestion')
    op.drop_index(op.f('ix_suggestion_accepted'), table_name='suggestion')
    op.drop_index(op.f('ix_media_suggestion_id'), table_name='media')
    # ### end Alembic commands ###
