"""user prefer_anonymous

Revision ID: ca79faf2b42e
Revises: 467458459309
Create Date: 2026-06-10 11:31:46.616737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca79faf2b42e'
down_revision: Union[str, Sequence[str], None] = '467458459309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prefer_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'prefer_anonymous')
    # ### end Alembic commands ###
