"""is_bot_blocked

Revision ID: fd78cff4867c
Revises: b06148c7d0d3
Create Date: 2026-02-18 00:17:00.476517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd78cff4867c'
down_revision: Union[str, Sequence[str], None] = 'b06148c7d0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_bot_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_bot_blocked')
    # ### end Alembic commands ###
