import contextvars
from typing import Protocol, overload

from aiogram import Bot


class BotRegistryProtocol(Protocol):
    @property
    def bot_settings(self) -> dict: ...

    @property
    def allowed_updates(self) -> list[str]: ...

    @allowed_updates.setter
    def allowed_updates(self, value): ...

    def register(self, bot: Bot) -> None: ...

    def get(self, bot_id: int) -> Bot | None: ...

    def get_or_create(self, bot_id: int, token: str) -> Bot: ...

    def remove(self, bot_id: int): ...

    def get_all(self) -> list[Bot]: ...

    def get_current(self) -> Bot | None: ...

    def set_current(self, bot: Bot) -> contextvars.Token[Bot | None]: ...

    def reset_current(self, token: contextvars.Token[Bot | None]) -> None: ...

    @overload
    async def with_bot(self, bot_id: int, /, *, token: str | None = None): ...

    @overload
    async def with_bot(self, bot: Bot, /): ...

    async def close(self) -> None: ...
