from collections.abc import Sequence
from typing import Any, Protocol

from core.schemas.objects import UserStats
from database.dto import (
    SuggestionBaseDTO,
    SuggestionFullDTO,
    UserBotDTO,
    UserBotStats,
    UserDTO,
    UserProfileDTO,
)


class UserRepositoryProtocol(Protocol):
    async def get_by_id(self, user_id: int) -> UserDTO | None: ...

    async def update(self, user_id: int, **data) -> None: ...

    async def get_or_create(self, prep_user_dto: UserDTO) -> UserDTO: ...

    async def create(self, dto: UserDTO) -> UserDTO: ...

    async def count(self) -> int: ...


class UserProfileRepositoryProtocol(Protocol):
    async def get_by_id(self, user_id: int) -> UserProfileDTO | None: ...

    async def get_many(
        self, limit: int = 10, offset: int = 0, order_desc: bool = False
    ) -> Sequence[UserProfileDTO]: ...

    async def get_or_create(self, user_id: int) -> UserProfileDTO: ...

    async def create(self, user_id: int) -> UserProfileDTO: ...

    async def update(self, user_id: int, **data) -> None: ...

    async def get_active(self) -> Sequence[UserProfileDTO]: ...

    async def get_admins(self) -> Sequence[UserProfileDTO]: ...

    async def get_banned(self) -> Sequence[UserProfileDTO]: ...

    async def count(self) -> int: ...

    async def admins_count(self) -> int: ...

    async def banned_count(self) -> int: ...

    async def bot_user_stats(self) -> Any: ...

    async def active_count(self) -> int: ...

    async def get_active_ids(self, after_id: int | None, limit: int) -> Sequence[int]: ...

    async def decline_all_suggestions(self, user_id: int) -> None: ...


class SuggestionRepositoryProtocol(Protocol):
    async def get_by_id(self, suggestion_id: int) -> SuggestionFullDTO | None: ...

    async def update(self, suggestion_id: int, **data: Any): ...

    async def save(self, dto: SuggestionBaseDTO): ...

    async def create(
        self,
        author_id: int,
        anonymous: bool,
        mediainfo: list[Any],
        caption: str | None,
        media_group_id: str | None,
        forwarded_from: str | None,
    ): ...

    async def get_active(self, limit=10, offset=0) -> Sequence[SuggestionFullDTO]: ...

    async def user_stats(self, user_id: int) -> UserStats | None: ...

    async def count(self) -> int: ...


class MediaRepositoryProtocol(Protocol):
    async def count(self) -> int: ...


class UserBotStatsRepositoryProtocol(Protocol):
    async def get(self) -> UserBotStats: ...


class UserBotRepositoryProtocol(Protocol):
    async def get(self, bot_id: int) -> UserBotDTO | None: ...

    async def get_active(self) -> Sequence[UserBotDTO]: ...

    async def get_by_owner_id(self, owner_id: int) -> Sequence[UserBotDTO]: ...

    async def create(
        self,
        token: str,
        bot_id: int,
        username: str,
        owner_id: int,
        channel_id: int,
        channel_name: str,
    ) -> None: ...

    async def update(self, bot_id: int, **data: Any): ...

    async def save(self, dto: UserBotDTO): ...
