from collections.abc import Sequence
from typing import Any, Protocol

from aiogram.types import Message

from core.schemas.objects import UserStats
from database.dto import SuggestionBaseDTO, SuggestionFullDTO, UserDTO, UserProfileDTO


class UserServiceProtocol(Protocol):
    async def get(self, user_id: int) -> UserDTO | None: ...

    async def create(self, prep_user_dto: UserDTO) -> UserDTO: ...

    async def get_or_create(self, prep_user_dto: UserDTO) -> UserDTO: ...

    async def update(self, user_id: int, **data: Any) -> None: ...

    async def save(self, user_dto: UserDTO) -> None: ...


class UserProfileServiceProtocol(Protocol):
    async def get_or_create(self, user_id: int) -> UserProfileDTO: ...

    async def create(self, user_id: int) -> UserProfileDTO: ...

    async def get(self, user_id: int) -> UserProfileDTO | None: ...

    async def get_many(self, limit: int = 10, offset: int = 0, order_desc: bool = False): ...

    async def update(self, user_id: int, **data: Any) -> None: ...

    async def save(self, profile_dto: UserProfileDTO) -> None: ...

    async def get_active(self) -> Sequence[UserProfileDTO]: ...

    async def get_admins(self) -> Sequence[UserProfileDTO]: ...

    async def decline_suggestion(self, profile_dto: UserProfileDTO) -> None: ...


class SuggestionServiceProtocol(Protocol):
    async def get(self, suggestion_id: int) -> SuggestionFullDTO: ...

    async def get_active(self) -> Sequence[SuggestionFullDTO]: ...

    async def create(
        self, author_dto: UserDTO, album: Sequence[Message], anonymous: bool = False
    ) -> SuggestionFullDTO: ...

    async def update(self, suggestion_dto: SuggestionBaseDTO) -> None: ...

    async def update_by_id(self, suggestion_id: int, **data: Any) -> None: ...

    async def get_user_stats(self, user_dto: UserDTO) -> UserStats: ...
